[package]
name = "xel"
version = "0.1.0"
authors = ["koka <koka.code@gmail.com>"]

[[bin]]
name = "xel"
path = "src/bin/main.rs"

[dependencies]
serde = "1.0.27"
serde_derive = "1.0.27"
serde_json = "1.0.9"
num = "0.1.42"
